apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: petclinic
spec:
  rules:
  - host: petclinic.40.74.44.198.nip.io
    http:
      paths:
      - backend:
          serviceName: petclinic-service
          servicePort: 80
        path: /
      - backend:
          serviceName: petclinic-service
          servicePort: 80
        path: /manage/health
      - backend:
          serviceName: petclinic-service
          servicePort: 80
        path: /manage/info